name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  sync-homebrew:
    name: Delegate Homebrew Update
    uses: JacksonFergusonDev/ci-cd-tooling/.github/workflows/update-homebrew-local.yml@main
    with:
      tag: ${{ github.ref_name }}
      formula_path: "Formula/focal.rb"
    secrets:
      TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
